base/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.HomeView, name="home"),
   path('addTransaction', views.AddTransaction, name="addTransaction"),
   path('addCategory', views.AddCategory, name="addCategory"),
   path('deleteTransaction/<int:id>', views.deleteTransaction, name='deleteTransaction'),
   path('login', views.LoginUser, name='login'),
   path('register', views.RegisterUser, name='register'),
   path('logout', views.LogoutUser, name='logout'),
]

expense/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('base.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    income = models.IntegerField()
    expenses = models.IntegerField(default=0)
    balance = models.IntegerField(null=True)

    def __str__(self):
        return self.user.username.capitalize()

class Categories(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Expense(models.Model):
    EXPENSETYPE = {
        ('Expense', 'Expense'),
        ('Income', 'Income'),
    }
    user = models.ForeignKey(User, on_delete=CASCADE)
    description = models.CharField(max_length=50)
    cost = models.IntegerField(default=True)
    category = models.ForeignKey(Categories,on_delete=CASCADE, blank=True, null=True)
    type = models.CharField(max_length=50, default='Expense', choices=EXPENSETYPE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.description

    @property
    def isExpense(self):
        return (self.type == 'Expense')

base/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    password1 = forms.CharField(label=("Enter Password"), widget=forms.PasswordInput(attrs={'placeholder':'Enter 8 Digit Alphanumeric Password'}))
    password2 = forms.CharField(label=("Confirm Password"), widget=forms.PasswordInput(attrs={'placeholder':'Confirm Password'}))
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {
            'username':None,
            'email':None,
        }
        widgets = {
            'username': forms.TextInput(attrs={'placeholder':'Enter Username...'}),
            'email': forms.EmailInput(attrs={'placeholder':'Enter Email...'}),
        }

base/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required

from .forms import CreateUserForm
from .models import Expense, UserProfile, Categories
from .decorators import unauthenticated_user


# Create your views here.

# Authentocation
@unauthenticated_user
def LoginUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username= username, password = password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Credentials Incorrect')
            return redirect('login')

    return render(request, 'auth/login.html')

@unauthenticated_user
def RegisterUser(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        balance = request.POST.get('balance')
        if form.is_valid():
            user = form.save()
            UserProfile.objects.create(user=user, balance=balance, income=balance).save()
            messages.success(request, f'Account Created!')
            return redirect('login')
    else:
        form = CreateUserForm()

    context = { 
        'form':form,
    }
    return render(request, 'auth/register.html', context)

def LogoutUser(request):
    logout(request)
    return redirect('login')

def is_valid_queryparam(param):
    return param != '' and param is not None

@login_required(login_url='login')
def HomeView(request):
    userProfile = UserProfile.objects.get(user = request.user)
    expenses = Expense.objects.filter(user = request.user)
    categories = Categories.objects.all()
    category = request.GET.get('category')

    # For Filtering
    if is_valid_queryparam(category) and category != 'all':
        expenses = expenses.filter(category__name=category)
    
    context = {
        'user_profile':userProfile,
        'expenses':expenses,
        'categories':categories,
    }
    return render(request, 'base/home.html',context)

def AddTransaction(request):
    userProfile = UserProfile.objects.get(user = request.user)

    if request.POST:
        # Getting the Input values and Updating in Expense Model
        description = request.POST.get('description')
        amount = request.POST.get('amount')
        category = request.POST.get('category')
        transaction_type = request.POST.get('transaction-type')
        if int(amount) > userProfile.balance:
                messages.error(request, "Amount Exceeds your Balance")
                return redirect('home')
        expense = Expense(user=request.user,description=description, category=Categories.objects.get(name=category), cost=amount, type=transaction_type)
        expense.save()
        # Updating Balance, Income and Expenses
        if transaction_type == 'Expense':
            userProfile.balance -= int(amount)
            userProfile.expenses += int(amount)
        else:
            userProfile.balance += int(amount)
            userProfile.income += int(amount)

        userProfile.save()

    return redirect('home')

def deleteTransaction(request, id):
    Expense.objects.get(id = id).delete()
    return redirect('home')

def AddCategory(request):
    if request.POST:
        category = request.POST.get('category').capitalize()
        print(category)
        Categories.objects.create(name=category).save()
    return redirect('home')

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Expense Manager</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static '/css/splide.min.css' %}" />
    <link rel="stylesheet" href="{% static '/css/main.css' %}" />
  </head>

  <body>
    {% block start %} {% endblock %}
  </body>
  <script src="{% static '/js/script.js' %}"></script>
  <script src="{% static '/js/splide.min.js' %}"></script>

  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"
  ></script>
</html>

base/templates/base/category_modal.html
<div class="modal category-modal hidden">
  <button class="close-modal">&times;</button>
  <h3>Add new Category</h3>
  <form action="{% url 'addCategory' %}" id="form" method="POST">
    {% csrf_token %}
    <div>
      <label for="text">Category Name:</label>
      <input
        type="text"
        required
        name="category"
        id="text"
        placeholder="Enter category..."
      />
    </div>
    <button class="btn" type="submit">Add Category</button>
  </form>
</div>

base/templates/base/content.html
<h4>Your Balance</h4>
    <h1 id="balance">₹ {{ user_profile.balance }}</h1>
    <div class="inc-exp-container">
      <div>
        <h4>Income</h4>
        <p id="money-plus" class="money plus">+₹ {{ user_profile.income }}</p>
      </div>
      <div>
        <h4>Expense</h4>
        <p id="money-minus" class="money minus">
          -₹ {{ user_profile.expenses }}
        </p>
      </div>
    </div>
    <h3>Top Picks:</h3>
    <div class="splide">
      <div class="splide__track">
        <ul class="splide__list">
          {% for expense in expenses|slice:"4" %}
          <li class="splide__slide category-card">
            <div class="title">{{ expense.description }}</div>
            <div class="category">{{ expense.category }}</div>
            <div class="amount">₹{{ expense.cost }}</div>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>

base/templates/base/history.html
<div class="btn-panel">
    <button class="btn add-transaction" onclick="openTransactionModal()">
      Add Transaction
    </button>
    <button class="btn add-category" onclick="openCategoryModal()">
      Add category
    </button>
  </div>
  <div class="filter-area">
    <h3>History:</h3>
    <form method="GET" action=".">
      <div class="filter-form">
        <label for="category">Category: </label>
        <select name="category" id="id_category">
          <option value="all" selected>All</option>
          {% for category in categories %}
          <option value="{{ category }}">{{ category }}</option>
          {% endfor %}
        </select>
        <button class="btn" type="submit">Go</button>
      </div>
    </form>
  </div>
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Description</th>
          <th>Type</th>
          <th>Category</th>
          <th>Amount</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for expense in expenses %} {% if expense.isExpense %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ expense.description }}</td>
          <td>{{ expense.type }}</td>
          <td>{{ expense.category }}</td>
          <td class="table-danger">-₹{{ expense.cost }}</td>
          <td align="center">
            <a href="{% url 'deleteTransaction' expense.id %}"  class="delete-btn">
            <i class="fas fa-times"></i>
            </a>
          </td>
        </tr>
        {% else %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ expense.description }}</td>
          <td>{{ expense.type }}</td>
          <td>{{ expense.category }}</td>
          <td class="table-success">+₹{{ expense.cost }}</td>
          <td align="center">
            <a href="{% url 'deleteTransaction' expense.id %}"  class="delete-btn">
            <i class="fas fa-times"></i>
            </a>
          </td>
          {% endif %} {% empty %}
          <tr>
            <td colspan="6" align="center">No Transaction Yet</td>
          </tr>
          {% endfor %}
        </tr>
      </tbody>
    </table>
  </div>

base/templates/base/home.html
{% extends "base/base.html" %} {% load static %} {% block start %}
<div class="header mt-3 container outer-container">
  <div class="main-title">Expense Manager</div>
  <div class="user-area">
    <div class="username">Welcome, {{ user.username|capfirst }}</div>
    <a href="{% url 'logout' %}" class="logout-icon">
      <i class="fa-solid fa-arrow-right-from-bracket"></i>
    </a>
  </div>
</div>
<div class="container content-area">
  <div class="content-container outer-container">
    {% include 'base/content.html' %}
  </div>
  <div class="history-container outer-container">
    {% include 'base/history.html' %}
  </div>
</div>

<!-- Modal Section -->
<!-- Add Transaction -->
{% include 'base/transaction_modal.html' %} 
{% include 'base/category_modal.html' %}

<div class="overlay hidden"></div>
{% endblock %}

base/templates/base/transaction_modal.html
<div class="modal transaction-modal hidden">
  <button class="close-modal">&times;</button>
  <h3>Add new transaction</h3>
  <form action="{% url 'addTransaction' %}" id="form" method="POST">
    {% csrf_token %}
    <div>
      <label for="text">Transaction Description:</label>
      <input
        type="text"
        required
        name="description"
        id="text"
        placeholder="Enter text..."
      />
    </div>
    <div>
      <label for="amount">Amount</label>
      <input
        type="number"
        required
        name="amount"
        id="amount"
        placeholder="Enter amount..."
      />
    </div>
    <div>
      <label for="text">Category:</label>
      <select name="category" class="form-select" required>
        {% for category in categories %}
        <option value="{{ category.name }}">{{ category.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div>
      <label for="text">Transaction Type:</label>
      <select name="transaction-type" class="form-select" required>
        <option value="Income">Income</option>
        <option value="Expense" selected>Expense</option>
      </select>
    </div>
    <button class="btn" type="submit">Add transaction</button>
  </form>
</div>